using System;
using System.Timers;

namespace WindowsSipPhone.Core.Transactions
{
    /// <summary>
    /// RFC 3261 Section 17.2.1 - INVITE Server Transaction (IST)
    /// Handles an incoming INVITE request and the responses the TU sends for it.
    ///
    /// State machine (RFC 3261 Figure 7):
    ///   Proceeding --(TU sends 2xx)--&gt; Terminated (transaction destroyed immediately,
    ///                                    ACK/retransmission handled by the dialog, not here)
    ///   Proceeding --(TU sends 3xx-6xx)--&gt; Completed --(ACK received)--&gt; Confirmed --(Timer I)--&gt; Terminated
    ///   Completed --(Timer H, no ACK)--&gt; Terminated (transaction error reported to TU)
    /// </summary>
    public class InviteServerTransaction : SipTransaction
    {
        private string _lastResponse = string.Empty;
        private bool _isReliableTransport;

        // RFC 3261 Section 17.2.1 - Timer H: time to wait for ACK (64*T1)
        private const int TimerH = 64 * T1;
        // Timer I: wait time in Confirmed state for unreliable transports (T4)
        private const int TimerI = T4;

        public InviteServerTransaction(string transactionId, bool isReliableTransport = true)
            : base(transactionId, "INVITE", true)
        {
            _isReliableTransport = isReliableTransport;

            // RFC 3261 17.2.1: as soon as the INVITE is received, the
            // transaction is in the Proceeding state (a 100 Trying is
            // typically generated by the TU almost immediately after).
            ChangeState(TransactionState.Proceeding);
        }

        /// <summary>
        /// Called by the TU (SipPhoneService) to send a response for this INVITE.
        /// </summary>
        public void SendResponse(string responseMessage)
        {
            var statusCode = ExtractStatusCode(responseMessage);

            if (statusCode >= 100 && statusCode < 200)
            {
                // Provisional response - stay in Proceeding, no timers needed
                SendMessage(responseMessage);
                return;
            }

            if (statusCode >= 200 && statusCode < 300)
            {
                // RFC 3261 17.2.1: for a 2xx response, the server transaction
                // is destroyed as soon as it's passed to the transport - the
                // ACK and any retransmissions are handled by the dialog/UAS
                // core, not this transaction.
                SendMessage(responseMessage);
                ChangeState(TransactionState.Terminated);
                return;
            }

            // 3xx-6xx: enter Completed, start retransmission (Timer G, reliable
            // transports skip retransmission) and Timer H (ACK wait)
            _lastResponse = responseMessage;
            SendMessage(responseMessage);
            ChangeState(TransactionState.Completed);

            if (!_isReliableTransport)
            {
                StartTimer(T1); // Timer G - retransmit response until ACK
            }
            else
            {
                StartTimer(TimerH); // Reliable transport: just wait for ACK/timeout
            }
        }

        /// <summary>
        /// Process an incoming message for this transaction: a retransmitted
        /// INVITE (while Proceeding/Completed) or the ACK for a non-2xx response.
        /// </summary>
        public override void ProcessMessage(string sipMessage)
        {
            var method = ExtractMethod(sipMessage);

            if (string.Equals(method, "ACK", StringComparison.OrdinalIgnoreCase))
            {
                if (State == TransactionState.Completed)
                {
                    // RFC 3261 17.2.1: ACK for non-2xx moves Completed -> Confirmed
                    ChangeState(TransactionState.Confirmed);
                    StopTimer();

                    if (!_isReliableTransport)
                    {
                        StartTimer(TimerI);
                    }
                    else
                    {
                        // Reliable transport: move directly to Terminated
                        ChangeState(TransactionState.Terminated);
                    }
                }
                return;
            }

            if (string.Equals(method, "INVITE", StringComparison.OrdinalIgnoreCase))
            {
                // Retransmitted request while we're still Proceeding or Completed:
                // resend whatever the TU last gave us (RFC 3261 17.2.1).
                if (State == TransactionState.Completed && !string.IsNullOrEmpty(_lastResponse))
                {
                    SendMessage(_lastResponse);
                }
                // While Proceeding, nothing to retransmit until the TU responds.
            }
        }

        protected override void OnTimerElapsed(object? sender, ElapsedEventArgs e)
        {
            switch (State)
            {
                case TransactionState.Completed:
                    if (!_isReliableTransport)
                    {
                        // Timer G fired: retransmit the final response
                        SendMessage(_lastResponse);
                        // Exponential backoff, capped at T2, until Timer H would fire
                        StartTimer(T2);
                    }
                    else
                    {
                        // Timer H fired with no ACK: transaction failed
                        ChangeState(TransactionState.Terminated);
                        OnTransactionFailed("INVITE server transaction timed out waiting for ACK");
                    }
                    break;

                case TransactionState.Confirmed:
                    // Timer I fired: done absorbing ACK retransmissions
                    ChangeState(TransactionState.Terminated);
                    break;
            }
        }

        private int ExtractStatusCode(string sipMessage)
        {
            var lines = sipMessage.Split(new[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
            if (lines.Length > 0)
            {
                var parts = lines[0].Split(' ');
                if (parts.Length >= 2 && int.TryParse(parts[1], out int code))
                {
                    return code;
                }
            }
            return 0;
        }

        private string ExtractMethod(string sipMessage)
        {
            var lines = sipMessage.Split(new[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
            if (lines.Length > 0)
            {
                var parts = lines[0].Split(' ');
                if (parts.Length > 0)
                {
                    return parts[0];
                }
            }
            return string.Empty;
        }
    }
}
